version: '3.7'

services:
  covid19-backend:
    container_name: covid19-backend
    image: bhavik3jain/bhavik-services-covid19-backend:latest
    ports:
      - '8083:8083'
    environment:
      COVID_19_BE_PORT: 8083
      COVID19_DB_HOST: ec2-3-232-92-90.compute-1.amazonaws.com
      COVID_DB_PORT: 5432
      COVID_DB_NAME: dfhodd20lunv5a
      COVID19_DB_USER: bppvdwscrvugdt
      COVID19_DB_PASSWORD: b460064ea052a697cf6830f1575ccbf5832a69449e298f180b9ac9896703705f
