CREATE SCHEMA covid19_data
  CREATE TABLE IF NOT EXISTS covid19_state_data(
    id SERIAL,
    date TEXT NOT NULL,
    data_quality_grade TEXT,
    death INTEGER,
    death_confirmed INTEGER,
    death_increase INTEGER,
    death_probable INTEGER,
    fips TEXT,
    hospitalized_cumulative INTEGER,
    hospitalized_currently INTEGER,
    hospitalized_increase INTEGER,
    in_icu_cumulative INTEGER,
    in_icu_currently INTEGER,
    negative INTEGER,
    negative_tests_antibody INTEGER,
    negative_tests_people_antibody INTEGER,
    negative_tests_viral INTEGER,
    on_ventilator_cumulative INTEGER,
    on_ventilator_currently INTEGER,
    pending INTEGER,
    positive INTEGER,
    positive_cases_viral INTEGER,
    positive_increase INTEGER,
    positive_tests_antibody INTEGER,
    positive_tests_antigen INTEGER,
    positive_tests_people_antibody INTEGER,
    positive_tests_people_antigen INTEGER,
    positive_tests_viral INTEGER,
    probable_cases INTEGER,
    recovered INTEGER,
    state TEXT NOT NULL,
    total_test_encounters_viral INTEGER,
    total_test_results INTEGER,
    total_test_results_increase INTEGER,
    total_test_results_source INTEGER,
    total_tests_antibody INTEGER,
    total_tests_antigen INTEGER,
    total_tests_people_antibody INTEGER,
    total_tests_people_antigen INTEGER,
    total_tests_people_viral INTEGER,
    total_tests_viral INTEGER,
    PRIMARY KEY(date, state)
  )
;
